-- CREATE USER TABLE
CREATE TABLE IF NOT EXISTS USER (
                                    USER_ID VARCHAR(255) NOT NULL,
                                    PHONE VARCHAR(15) NOT NULL UNIQUE ,
                                    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    PRIMARY KEY (USER_ID)
);

CREATE UNIQUE INDEX USER_ID_INDEX ON USER (USER_ID);
-- CREATE ROLE TABLE
CREATE TABLE IF NOT EXISTS ROLE (
                                    ROLE_ID VARCHAR(255) NOT NULL,
                                    ROLE_DESCRIPTION VARCHAR(255),
                                    ROLE_NAME VARCHAR(255) NOT NULL UNIQUE,
                                    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                    PRIMARY KEY (ROLE_ID)
);
CREATE UNIQUE INDEX ROLE_ID_INDEX ON ROLE (ROLE_ID);

-- CREATE USER-ROLES MAPPING TABLE
CREATE TABLE IF NOT EXISTS USER_ROLES (
                                          USER_ID VARCHAR(255) NOT NULL,
                                          ROLE_ID VARCHAR(255) NOT NULL,
                                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
                                          CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX USER_FK_INDEX ON USER_ROLES (USER_ID);
CREATE INDEX ROLE_FK_INDEX ON USER_ROLES (ROLE_ID);